name: "Auto Music PR"
on:
  push:
    branches:
      - feature/edit-music-files  # 해당 브랜치에서만 실행

jobs:
  auto-create-pr:
    # if: github.run_number == 1  # 처음 push에만 실행
    runs-on: ubuntu-latest
    steps:
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - uses: actions/checkout@v4
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.AUTO_MUSIC_PR }}
        head: ${{ github.ref }}
        base: master
        title: ${{ github.event.head_commit.message }}
