name: "Auto Music PR"
on:
  create:
    branches:
      - feature/edit-music-files

jobs:
  auto-create-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.AUTO_MUSIC_PR }}
        head: ${{ github.ref }}
        base: master
        title: ${{ github.event.head_commit.message }}
